from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image
)
from reportlab.lib.styles import getSampleStyleSheet
import os


def clean_text(line):
    """
    Remove markdown formatting generated by Gemini
    """

    line = line.replace("**", "")
    line = line.replace("*", "")
    line = line.replace("#", "")

    return line.strip()


def generate_pdf(
    report_text,
    merged_data,
    inspection_image_map
):
    """
    Generate final DDR PDF with:
    - structured report text
    - section-wise images
    """

    # Create output folder
    os.makedirs("output", exist_ok=True)

    output_path = "output/final_ddr_report.pdf"

    styles = getSampleStyleSheet()

    doc = SimpleDocTemplate(output_path)

    story = []

    # -----------------------------
    # Title
    # -----------------------------
    story.append(
        Paragraph(
            "Detailed Diagnostic Report (DDR)",
            styles["Heading1"]
        )
    )

    story.append(Spacer(1, 20))

    # -----------------------------
    # Add AI Generated Report Content
    # -----------------------------
    for line in report_text.split("\n"):

        cleaned_line = clean_text(line)

        if cleaned_line:

            if cleaned_line.startswith(
                ("1.", "2.", "3.", "4.", "5.", "6.")
            ):
                story.append(
                    Paragraph(
                        cleaned_line,
                        styles["Heading2"]
                    )
                )
            else:
                story.append(
                    Paragraph(
                        cleaned_line,
                        styles["Normal"]
                    )
                )

            story.append(Spacer(1, 10))

    story.append(Spacer(1, 20))

    # -----------------------------
    # Area-wise images section
    # -----------------------------
    story.append(
        Paragraph(
            "Area-wise Images",
            styles["Heading1"]
        )
    )

    story.append(Spacer(1, 20))

    for area, details in merged_data.items():

        # Skip thermal summary
        if area == "thermal_summary":
            continue

        story.append(
            Paragraph(
                area,
                styles["Heading2"]
            )
        )

        story.append(
            Paragraph(
                details["issue"],
                styles["Normal"]
            )
        )

        story.append(Spacer(1, 10))

        page_num = details.get("page")
        image_index = details.get("image_index", 0)

        if page_num in inspection_image_map:

            page_images = inspection_image_map[page_num]

            # Skip logo/header image
            actual_images = page_images[1:]

            if not actual_images:
                actual_images = page_images

            # Prevent index overflow
            if image_index >= len(actual_images):
                image_index = len(actual_images) - 1

            img_path = actual_images[image_index]

            try:
                img = Image(
                    img_path,
                    width=250,
                    height=180
                )

                story.append(img)
                story.append(Spacer(1, 10))

            except Exception as e:
                print(
                    f"Error loading image: {img_path}"
                )

                story.append(
                    Paragraph(
                        "Image Not Available",
                        styles["Normal"]
                    )
                )

        else:
            story.append(
                Paragraph(
                    "Image Not Available",
                    styles["Normal"]
                )
            )

        story.append(Spacer(1, 20))

    # -----------------------------
    # Build PDF
    # -----------------------------
    doc.build(story)

    return output_path