from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    Image
)
from reportlab.lib.styles import getSampleStyleSheet
import os
import glob


def clean_text(line):
    """
    Remove unwanted markdown formatting
    generated by LLM responses.
    
    Example:
    '**Hall**' -> 'Hall'
    '* Issue' -> 'Issue'
    """

    line = line.replace("**", "")
    line = line.replace("*", "")
    line = line.replace("#", "")

    return line.strip()


def add_images_to_pdf(story, folder_path, styles, section_title):
    """
    Add extracted images to PDF appendix section.

    Parameters:
    story -> PDF content list
    folder_path -> folder containing images
    styles -> reportlab styles
    section_title -> heading name
    """

    # Add section title
    story.append(
        Paragraph(section_title, styles["Heading2"])
    )
    story.append(Spacer(1, 12))

    # Get all image files
    image_files = glob.glob(
        os.path.join(folder_path, "*")
    )

    if not image_files:
        story.append(
            Paragraph(
                "Image Not Available",
                styles["Normal"]
            )
        )
        story.append(Spacer(1, 12))
        return

    for img_path in image_files[:5]:
        try:
            # Add image filename
            story.append(
                Paragraph(
                    os.path.basename(img_path),
                    styles["Normal"]
                )
            )

            # Add image
            img = Image(
                img_path,
                width=300,
                height=200
            )

            story.append(img)
            story.append(Spacer(1, 20))

        except Exception as e:
            story.append(
                Paragraph(
                    f"Could not load image: {img_path}",
                    styles["Normal"]
                )
            )


def generate_pdf(report_text):
    """
    Generate final structured DDR PDF report.

    Steps:
    1. Clean Gemini markdown output
    2. Add proper formatting
    3. Add extracted images appendix
    """

    # Create output folder
    os.makedirs("output", exist_ok=True)

    output_path = "output/final_ddr_report.pdf"

    # Load default styles
    styles = getSampleStyleSheet()

    # Create PDF document
    doc = SimpleDocTemplate(output_path)

    story = []

    # Add report title
    story.append(
        Paragraph(
            "Detailed Diagnostic Report (DDR)",
            styles["Heading1"]
        )
    )

    story.append(Spacer(1, 20))

    # Process report text line by line
    for line in report_text.split("\n"):

        cleaned_line = clean_text(line)

        if cleaned_line:

            # Detect headings
            if cleaned_line.startswith("1.") \
                    or cleaned_line.startswith("2.") \
                    or cleaned_line.startswith("3.") \
                    or cleaned_line.startswith("4.") \
                    or cleaned_line.startswith("5.") \
                    or cleaned_line.startswith("6."):

                story.append(
                    Paragraph(
                        cleaned_line,
                        styles["Heading2"]
                    )
                )

            else:
                story.append(
                    Paragraph(
                        cleaned_line,
                        styles["Normal"]
                    )
                )

            story.append(Spacer(1, 12))

    # Add page break before appendix
    story.append(PageBreak())

    # Add image appendix title
    story.append(
        Paragraph(
            "Appendix: Extracted Images",
            styles["Heading1"]
        )
    )

    story.append(Spacer(1, 20))

    # Add inspection images
    add_images_to_pdf(
        story,
        "output/inspection_images",
        styles,
        "Inspection Images"
    )

    # Add thermal images
    add_images_to_pdf(
        story,
        "output/thermal_images",
        styles,
        "Thermal Images"
    )

    # Build final PDF
    doc.build(story)

    return output_path